import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createCafe,periodKeys } from '../src/game/core/state';
import { applyAction } from '../src/game/core/actions';
import { advance } from '../src/game/core/simulation';
import { validLayout,path,seats,entry,iso,fromIso } from '../src/game/core/grid';
import { ITEMS,RECIPES } from '../src/game/core/catalog';
import type { Player } from '../src/types/game';
const start=Date.UTC(2026,8,13,12);
function setup(){const c=createCafe('test','Café de teste',start);const p:Player={uid:'test',displayName:'Chef',username:'chef',role:'player',level:1,xp:0,coins:3000,gems:0,popularity:50};return {c,p};}
function action(c:ReturnType<typeof createCafe>,p:Player,a:Record<string,unknown>,now=start){return applyAction(c,p,{requestId:crypto.randomUUID(),...a} as any,now);}
test('starter layout is navigable and has four real seat/table pairs',()=>{const {c}=setup();assert.equal(validLayout(c),null);assert.equal(seats(c).length,4);for(let x=0;x<8;x++)for(let y=0;y<8;y++)assert.deepEqual(fromIso(iso(x,y).x,iso(x,y).y),{x,y});});
test('cooking reserves an actual stove; prevents locked recipes and insufficient funds',()=>{const {c,p}=setup();assert.throws(()=>action(c,p,{type:'cook',recipeId:'brigadeiro'}),/nível/i);action(c,p,{type:'cook',recipeId:'espresso',stoveId:'starter-0'});assert.equal(p.coins,2985);assert.throws(()=>action(c,p,{type:'cook',recipeId:'espresso',stoveId:'starter-0'}),/ocupado/);p.coins=0;assert.throws(()=>action(c,p,{type:'cook',recipeId:'espresso',stoveId:'starter-1'}),/Moedas/);});
test('collection is timed, supplies portions without paying sales, and cannot repeat',()=>{const {c,p}=setup();action(c,p,{type:'cook',recipeId:'pao_queijo'});const id=c.jobs[0].id;assert.throws(()=>action(c,p,{type:'collect',jobId:id},start+29999),/preparando/);action(c,p,{type:'collect',jobId:id},start+30000);assert.equal(p.coins,2970);assert.equal(p.xp,10);assert.equal(Object.values(c.counters)[0].portions,20);assert.throws(()=>action(c,p,{type:'collect',jobId:id},start+30001),/não encontrado/);});
test('spoiled food requires cleanup, including after a long offline interval',()=>{const {c,p}=setup();action(c,p,{type:'cook',recipeId:'espresso'});const {id,spoilsAt}=c.jobs[0];advance(c,p,start+86400000);assert.equal(c.jobs[0].id,id);assert.throws(()=>action(c,p,{type:'collect',jobId:id},spoilsAt),/estragou/);action(c,p,{type:'cleanStove',jobId:id},spoilsAt);assert.equal(c.jobs.length,0);});
test('full service loop moves guests and waiter, consumes food, pays and cleans',()=>{const {c,p}=setup();c.counters['starter-3']={recipeId:'espresso',name:'Café',portions:100,price:4,art:RECIPES[0].art};const seen=new Set<string>();let moved=false,carried=false,dirty=false;
 for(let t=start+250;t<=start+180000;t+=250){advance(c,p,t);for(const g of c.sim.customers){seen.add(g.state);moved ||=g.motion.path.length>1;}carried ||=c.sim.workers.some(w=>!!w.carrying);dirty ||=Object.keys(c.dirty).length>0;}
 assert.ok(moved);assert.ok(carried);assert.ok(dirty);assert.ok(c.progress.total.served>4,`Only ${c.progress.total.served} served`);assert.equal(p.coins,3000+c.progress.total.served*4);assert.ok(c.counters['starter-3'].portions<100);assert.deepEqual([...seen].sort(),['eating','leaving','waiting','walking']);});
test('clients lose patience without food and popularity falls',()=>{const {c,p}=setup();for(let t=start+250;t<=start+90000;t+=250)advance(c,p,t);assert.equal(p.coins,3000);assert.ok(p.popularity<50);});
test('layout rejects overlaps, outside cells, a blocked doorway and active storage',()=>{const {c,p}=setup();assert.throws(()=>action(c,p,{type:'move',id:'starter-0',x:2,y:1}),/existe/);assert.throws(()=>action(c,p,{type:'move',id:'starter-0',x:-1,y:1}),/dentro/);assert.throws(()=>action(c,p,{type:'move',id:'starter-0',...entry(8)}),/entrada/);action(c,p,{type:'cook',recipeId:'espresso'});assert.throws(()=>action(c,p,{type:'store',id:'starter-0'}),/receita/);});
test('buy-store-place-rotate-sell preserves ownership and economy',()=>{const {c,p}=setup();action(c,p,{type:'buy',itemId:'planta_verde'});assert.equal(p.coins,2820);const id=c.inventory[0].id;action(c,p,{type:'place',id,x:7,y:7});assert.equal(c.inventory.length,0);action(c,p,{type:'rotate',id});assert.equal(c.layout.find(f=>f.id===id)?.rotation,1);action(c,p,{type:'store',id});assert.equal(c.inventory[0].id,id);action(c,p,{type:'sell',id});assert.equal(p.coins,2892);assert.throws(()=>action(c,p,{type:'sell',id}),/não encontrado/);});
test('restoring an offline session does not manufacture sales or coins',()=>{const {c,p}=setup();c.counters['starter-3']={recipeId:'espresso',name:'Café',portions:50,price:4,art:RECIPES[0].art};advance(c,p,start+86400000);assert.equal(p.coins,3000);assert.equal(c.counters['starter-3'].portions,50);assert.equal(c.sim.customers.length,0);});
test('duplicate reward claims fail and Brazilian daily/weekly boundaries are stable',()=>{const {c,p}=setup();c.progress.daily.served=20;action(c,p,{type:'mission',missionId:'serve20'});assert.equal(p.coins,3150);assert.throws(()=>action(c,p,{type:'mission',missionId:'serve20'}),/já recebida/);assert.deepEqual(periodKeys(Date.UTC(2026,8,14,2,59)),{day:'2026-09-13',week:'2026-09-07'});assert.deepEqual(periodKeys(Date.UTC(2026,8,14,3)),{day:'2026-09-14',week:'2026-09-14'});});
test('expansions and staff upgrades validate level, funds and limits',()=>{const {c,p}=setup();assert.throws(()=>action(c,p,{type:'expand'}),/nível/);p.level=4;action(c,p,{type:'expand'});assert.equal(c.size,10);assert.equal(p.coins,500);action(c,p,{type:'upgrade',role:'waiter'});assert.equal(c.staff.waiter,2);assert.equal(p.coins,100);assert.throws(()=>action(c,p,{type:'upgrade',role:'owner'}),/inválido/);});
test('pathfinding never crosses solid furniture cells',()=>{const {c}=setup();const route=path(c,entry(8),{x:4,y:1});assert.ok(route);const occupied=new Set(c.layout.map(f=>`${f.x},${f.y}`));for(const p of route!)assert.ok(!occupied.has(`${p.x},${p.y}`));});
