"use client";
import AuthGuard from '@/components/AuthGuard';
import InviteModal from '@/components/InviteModal';
import TopBar from '@/components/TopBar';
import Icon from '@/components/Icon';
import { apiPost } from '@/lib/api';
import { db } from '@/lib/firebase';
import { collection,endAt,getDocs,limit,orderBy,query,startAt } from 'firebase/firestore';
import Link from 'next/link';
import { useEffect,useState } from 'react';
function Community(){const [term,setTerm]=useState(''),[tab,setTab]=useState('suggestions'),[players,setPlayers]=useState<any[]>([]),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[invite,setInvite]=useState(false),[busy,setBusy]=useState('');
 const load=async(mode:string)=>{setTab(mode);setLoading(true);setMessage('');try{if(mode==='discover'){const snap=await getDocs(query(collection(db,'publicProfiles'),orderBy('level','desc'),limit(24)));setPlayers(snap.docs.map(d=>d.data()).filter(p=>!p.disabled));}else{const d=await apiPost('/api/social/list',{mode});setPlayers(d.players||[]);}}catch(e){setMessage(e instanceof Error?e.message:'Tente novamente.');}finally{setLoading(false);}};
 useEffect(()=>{void load('suggestions');},[]);
 const follow=async(uid:string,action='follow')=>{setBusy(uid);try{await apiPost('/api/social/follow',{targetUid:uid,action});setMessage(action==='follow'?'Você está seguindo este café.':'Você deixou de seguir este café.');await load(tab);}catch(e){setMessage(e instanceof Error?e.message:'Tente novamente.');}finally{setBusy('');}};
 return <div className="game-app"><TopBar/><main className="social-page"><div className="social-title"><div><small>COMUNIDADE CAFÉVILLE</small><h1>Bons cafés. Novos amigos.</h1><p>Conheça a vizinhança e encontre seu próximo café favorito.</p></div><button className="green" onClick={()=>setInvite(true)}><Icon name="gift"/>Convidar amigos</button></div><div className="pills ranking-pills">{[['suggestions','Sugestões'],['following','Seguindo'],['followers','Seguidores'],['discover','Descobrir']].map(([k,v])=><button key={k} className={tab===k?'active':''} onClick={()=>load(k)}>{v}</button>)}</div><form className="community-search" onSubmit={async e=>{e.preventDefault();setLoading(true);setTab('discover');try{const v=term.trim().toLowerCase().replace(/^@/,'');const s=await getDocs(query(collection(db,'publicProfiles'),orderBy('usernameLower'),startAt(v),endAt(v+'\uf8ff'),limit(24)));setPlayers(s.docs.map(d=>d.data()).filter(p=>!p.disabled));}catch(e){setMessage(e instanceof Error?e.message:'Tente novamente.');}finally{setLoading(false);}}}><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Encontre um café por @usuário" required/><button>Buscar</button></form>{message&&<p role="status">{message}</p>}{loading?<p>Conhecendo a vizinhança…</p>:<div className="neighbor-grid">{players.map(p=><article className="neighbor-card" key={p.uid}><div className="neighbor-cover"><img src="/assets/cafeville-scene.png" alt="Ilustração do CaféVille"/></div><div className="neighbor-body"><img className="neighbor-avatar" src="/assets/game/characters/chef-0.svg" alt=""/><h2>{p.displayName}</h2><small>@{p.username}</small><p>{p.cafeName}</p><div className="neighbor-stats"><span>Nv. {p.level}</span><span>{p.popularity}%</span><span>{p.followersCount||0} seguidores</span></div>{p.reason&&<p className="suggestion-reason">{p.reason}</p>}<footer><Link href={`/jogador/${p.uid}`}>Visitar</Link><button disabled={busy===p.uid} onClick={()=>follow(p.uid,tab==='following'?'unfollow':'follow')}>{tab==='following'?'Deixar de seguir':'Seguir'}</button>{tab==='suggestions'&&<button onClick={async()=>{try{await apiPost('/api/social/action',{type:'dismiss',targetUid:p.uid});setPlayers(v=>v.filter(x=>x.uid!==p.uid));}catch(e){setMessage(e instanceof Error?e.message:'Tente novamente.');}}}>Agora não</button>}</footer></div></article>)}{!players.length&&<div className="empty-state"><Icon name="users" size={60}/><h2>A próxima amizade começa com um convite.</h2><p>Nenhum café nesta lista por enquanto.</p><button onClick={()=>setInvite(true)}>Convidar amigos</button></div>}</div>}</main><InviteModal open={invite} onClose={()=>setInvite(false)}/></div>;
}
export default function CommunityPage(){return <AuthGuard><Community/></AuthGuard>;}
