"use client";
import GameArt from '@/components/GameArt';
import AuthGuard from '@/components/AuthGuard';
import TopBar from '@/components/TopBar';
import Icon from '@/components/Icon';
import { apiPost } from '@/lib/api';
import { MISSIONS } from '@/game/core/catalog';
import { useState,useEffect } from 'react';
import type { FormEvent } from 'react';
const labels={dashboard:'Visão geral',players:'Jogadores',economy:'Economia',recipes:'Receitas',items:'Itens',events:'Eventos',gifts:'Presentes',missions:'Missões',logs:'Histórico'};
function Admin(){
 const [data,setData]=useState<any>(null),[tab,setTab]=useState('dashboard'),[term,setTerm]=useState(''),[players,setPlayers]=useState<any[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState<any>(null),[accessError,setAccessError]=useState('');
 const load=async()=>{const d=await apiPost('/api/admin/manage',{type:'dashboard'});setData(d);};
 useEffect(()=>{load().catch(e=>setAccessError(e.message));},[]);
 const send=async(payload:any)=>{setBusy(true);try{await apiPost('/api/admin/manage',{...payload,requestId:crypto.randomUUID()});setMessage('Operação concluída e registrada no histórico.');setEdit(null);await load();if(term){const d=await apiPost('/api/admin/manage',{type:'search',term});setPlayers(d.players||[]);}return true;}catch(e){setMessage(e instanceof Error?e.message:'Tente novamente.');return false;}finally{setBusy(false);}};
 const submit=(e:FormEvent<HTMLFormElement>,type:string)=>{e.preventDefault();const form=new FormData(e.currentTarget),payload:any={type};form.forEach((value,k)=>payload[k]=value);if('active'in payload)payload.active=payload.active==='true';for(const key of ['startAt','endAt'])if(payload[key])payload[key]=new Date(payload[key]).getTime();void send(payload);};
 if(!data)return <div className="game-app"><TopBar/><main className="social-page"><h1>{accessError||'Verificando acesso…'}</h1>{accessError&&<p>Somente contas com a função admin podem acessar este painel.</p>}</main></div>;
 const input=(name:string,label:string,value:any='',type='text')=><label>{label}<input name={name} type={type} defaultValue={value} required/></label>;
 const select=(name:string,label:string,list:any[],value?:string)=><label>{label}<select name={name} defaultValue={value}>{list.map(i=><option value={i.id} key={i.id}>{i.name||i.id}</option>)}</select></label>;
 return <div className="game-app"><TopBar/><main className="social-page admin-page"><div className="social-title"><div><small>ADMINISTRAÇÃO CAFÉVILLE</small><h1>Cuide da sua vila</h1><p>Jogadores, conteúdo e recompensas em um só lugar.</p></div><Icon name="chef" size={70}/></div><div className="pills ranking-pills">{Object.entries(labels).map(([k,v])=><button key={k} className={tab===k?'active':''} onClick={()=>{setTab(k);setEdit(null);}}>{v}</button>)}</div>{message&&<p className="admin-feedback" role="status">{message}</p>}
 {['dashboard','economy'].includes(tab)&&<><div className="admin-metrics"><article><Icon name="users" size={38}/><strong>{data.totals.players.toLocaleString('pt-BR')}</strong><span>Jogadores cadastrados</span></article><article><Icon name="coin" size={38}/><strong>{Math.floor(data.totals.coins).toLocaleString('pt-BR')}</strong><span>Moedas nos saldos</span></article><article><Icon name="book" size={38}/><strong>{data.recipes.length}</strong><span>Receitas no catálogo</span></article></div><section className="admin-info"><h2>Economia do CaféVille</h2><p>Saldo inicial: 3.000 moedas. Convites: 500 para quem convida e 250 para quem entra. Vendas consomem porções e são calculadas pelo servidor.</p><p>Presentes para todos ficam disponíveis na caixa de cada jogador e só podem ser resgatados uma vez.</p></section></>}
 {tab==='players'&&<><form className="community-search" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const d=await apiPost('/api/admin/manage',{type:'search',term});setPlayers(d.players||[]);}catch(e){setMessage(e instanceof Error?e.message:'Tente novamente.');}finally{setBusy(false);}}}><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Buscar @usuário ou e-mail exato" required/><button disabled={busy}>Buscar jogador</button></form><div className="admin-players">{players.map(p=><article key={p.uid}><h2>{p.displayName} <small>@{p.username}</small></h2><p>{p.email} · {p.disabled?'Desativado':'Ativo'}</p><p>Nível {p.level} · {p.xp} XP · {Math.floor(p.coins).toLocaleString('pt-BR')} moedas · {p.popularity}% popularidade</p><p>Última atividade: {p.lastSeenAt?new Date((p.lastSeenAt._seconds||p.lastSeenAt.seconds||0)*1000).toLocaleString('pt-BR'):'Não registrada'}</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void send({type:'coins',targetUid:p.uid,amount:f.get('amount')});}}><input type="number" name="amount" min={1} max={1000000} defaultValue={500} required/><button disabled={busy}>Enviar moedas</button></form><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void send({type:'gift',targetUid:p.uid,itemId:f.get('itemId')});}}><select name="itemId">{data.items.filter((i:any)=>['table','chair','plant','stove','counter','lamp','sofa','fridge'].includes(i.kind)).map((i:any)=><option value={i.id} key={i.id}>{i.name}</option>)}</select><button disabled={busy}>Enviar presente</button></form><button className="quiet" disabled={busy} onClick={()=>{if(confirm(`${p.disabled?'Reativar':'Desativar'} a conta de ${p.displayName}?`))void send({type:'disable',targetUid:p.uid,disabled:!p.disabled});}}>{p.disabled?'Reativar':'Desativar'} conta</button></article>)}</div></>}
 {tab==='recipes'&&<><div className="admin-catalog-list">{data.recipes.map((r:any)=><button key={r.id} onClick={()=>setEdit({...r,artId:data.recipes.find((x:any)=>x.art===r.art)?.id||r.id})}><img src={r.art} alt=""/><span>{r.name}<small>{r.active===false?'Inativa':`Nv. ${r.level} · ${r.seconds}s`}</small></span>Editar</button>)}</div><h2>{edit?'Editar receita':'Nova receita'}</h2><form key={edit?.id||'new-recipe'} className="admin-form" onSubmit={e=>submit(e,'recipe')}>
 {input('id','Identificador sem espaços',edit?.id||'')}{input('name','Nome',edit?.name||'')}{select('category','Categoria',['Bebidas','Salgados','Doces','Pratos'].map(id=>({id,name:id})),edit?.category)}{select('artId','Ilustração',data.recipes,edit?.artId)}
 {input('cost','Custo',edit?.cost||30,'number')}{input('price','Preço por porção',edit?.price||4,'number')}{input('portions','Porções',edit?.portions||20,'number')}{input('xp','XP',edit?.xp||10,'number')}{input('seconds','Preparo em segundos',edit?.seconds||30,'number')}{input('shelfSeconds','Prazo para recolher em segundos',edit?.shelfSeconds||1800,'number')}{input('level','Nível mínimo',edit?.level||1,'number')}{select('active','Disponibilidade',[{id:'true',name:'Ativa'},{id:'false',name:'Inativa'}],String(edit?.active!==false))}<button disabled={busy}>Salvar receita</button>{edit&&<button type="button" className="quiet" onClick={()=>setEdit(null)}>Criar outra</button>}</form></>}
 {tab==='items'&&<><div className="admin-catalog-list">{data.items.map((i:any)=><button key={i.id} onClick={()=>setEdit({...i,templateId:data.items.find((x:any)=>x.kind===i.kind)?.id})}><GameArt src={i.art} itemId={i.id}/><span>{i.name}<small>{i.price} moedas</small></span>Editar</button>)}</div><h2>{edit?'Editar item':'Novo item'}</h2><form key={edit?.id||'new-item'} className="admin-form" onSubmit={e=>submit(e,'item')}>{input('id','Identificador',edit?.id||'')}{input('name','Nome',edit?.name||'')}{select('templateId','Modelo visual',data.items,edit?.templateId)}{input('price','Preço',edit?.price||300,'number')}{input('level','Nível mínimo',edit?.level||1,'number')}{select('active','Disponibilidade',[{id:'true',name:'Ativo'},{id:'false',name:'Inativo'}],String(edit?.active!==false))}<button disabled={busy}>Salvar item</button>{edit&&<button type="button" className="quiet" onClick={()=>setEdit(null)}>Criar outro</button>}</form></>}
 {tab==='events'&&<><div className="admin-catalog-list">{data.events.map((e:any)=><button key={e.id} onClick={()=>setEdit(e)}>{e.name} · editar</button>)}</div><h2>{edit?'Editar evento':'Criar evento sazonal'}</h2><p>Os objetivos usam os atendimentos da semana corrente, inclusive os anteriores à abertura do evento.</p><form key={edit?.id||'new-event'} className="admin-form" onSubmit={e=>submit(e,'event')}>{input('id','Identificador',edit?.id||'')}{input('name','Nome do evento',edit?.name||'')}{input('description','Descrição',edit?.description||'')}{input('startAt','Início',edit?.startAt?new Date(edit.startAt).toISOString().slice(0,16):'','datetime-local')}{input('endAt','Fim',edit?.endAt?new Date(edit.endAt).toISOString().slice(0,16):'','datetime-local')}{input('target','Clientes na semana',edit?.target||50,'number')}{input('coins','Moedas de recompensa',edit?.coins||500,'number')}{input('xp','XP de recompensa',edit?.xp||100,'number')}{select('itemId','Presente opcional',[{id:'',name:'Sem item'},...data.items],edit?.itemId||'')}{select('recipeId','Receita em destaque',[{id:'',name:'Sem receita'},...data.recipes],edit?.recipeId||'')}{select('active','Disponibilidade',[{id:'true',name:'Ativo'},{id:'false',name:'Inativo'}],String(edit?.active!==false))}<button disabled={busy}>Salvar evento</button></form></>}
 {tab==='gifts'&&<><h2>Presente para toda a vila</h2><p>Cria uma campanha com resgate individual, disponível na caixa de presentes de todos os jogadores.</p><form className="admin-form" onSubmit={e=>submit(e,'campaign')}>{input('title','Mensagem do presente')}{input('coins','Moedas',500,'number')}{select('itemId','Item opcional',[{id:'',name:'Sem item'},...data.items.filter((i:any)=>!['floor','wall','door','window','theme'].includes(i.kind))])}<button disabled={busy}>Disponibilizar presente para todos</button></form><div className="admin-info">{data.campaigns.map((c:any)=><p key={c.id}>{c.title} · {c.coins} moedas</p>)}</div></>}
 {tab==='missions'&&<div className="admin-info"><h2>Missões validadas pelo jogo</h2>{MISSIONS.map(m=><p key={m.id}><b>{m.name}</b> · {m.period==='daily'?'Diária':m.period==='weekly'?'Semanal':'Conquista'} · Meta {m.target} · {m.coins} moedas e {m.xp} XP</p>)}</div>}
 {tab==='logs'&&<div className="admin-log-list">{data.logs.map((l:any)=><article key={l.id}><b>{l.type}</b><span>Destino: {l.targetUid}</span><small>Admin: {l.adminUid}</small><code>{JSON.stringify(l.payload||{amount:l.amount,giftId:l.giftId})}</code></article>)}{!data.logs.length&&<p>Nenhuma ação administrativa registrada.</p>}</div>}
 </main></div>;
}
export default function AdminPage(){return <AuthGuard><Admin/></AuthGuard>;}
