"use client";
import GameArt from '@/components/GameArt';
import { useEffect,useRef,useState } from 'react';
import Link from 'next/link';
import CafeGame from './CafeGame';
import Icon from './Icon';
import InviteModal from './InviteModal';
import { useGame } from '@/services/use-game';
import { MISSIONS,EXPANSIONS,isStyle } from '@/game/core/catalog';
import { missionKey } from '@/game/core/state';
import { CafeAudio } from '@/game/audio';
import { apiPost } from '@/lib/api';
import type { Action } from '@/types/game';
import { auth } from '@/lib/firebase';
import { signOut } from 'firebase/auth';
const money=(n:number)=>Math.floor(n).toLocaleString('pt-BR');
const duration=(n:number)=>n<60?`${n}s`:n<3600?`${Math.ceil(n/60)} min`:`${+(n/3600).toFixed(1)} h`;
const tabs=[['book','Receitas','recipes'],['shop','Loja','shop'],['chef','Equipe','staff'],['chair','Decorar','inventory'],['flag','Missões','missions'],['gift','Presentes','gifts']] as const;
const categories:Record<string,string>={Todos:'',Mesas:'table',Cadeiras:'chair',Fogões:'stove',Balcões:'counter',Decoração:'plant',Luzes:'lamp',Móveis:'sofa',Geladeiras:'fridge',Pisos:'floor',Paredes:'wall',Portas:'door',Janelas:'window',Temas:'theme'};
export default function GameView({demo=false}:{demo?:boolean}){
 const {state,busy,message,setMessage,error,online,run,levelUp,setLevelUp,refresh}=useGame(demo);
 const [panel,setPanel]=useState('recipes'),[filter,setFilter]=useState('Todas'),[shopFilter,setShopFilter]=useState('Todos'),[editing,setEditing]=useState(false),[selected,setSelected]=useState(''),[placing,setPlacing]=useState(''),[rotation,setRotation]=useState(0),[stove,setStove]=useState(''),[invite,setInvite]=useState(false),[sound,setSound]=useState(false),[now,setNow]=useState(Date.now()),[period,setPeriod]=useState<'daily'|'weekly'|'total'>('daily'),[suggestions,setSuggestions]=useState<any[]>([]),[gifts,setGifts]=useState<any[]>([]),[rename,setRename]=useState(false),[newName,setNewName]=useState('');
 const audio=useRef(new CafeAudio()),previousOpen=useRef(true),serverOffset=useRef(0);
 useEffect(()=>{if(state)serverOffset.current=state.now-Date.now();},[state]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),500);return()=>{clearInterval(timer);audio.current.stop();};},[]);
 useEffect(()=>{if(demo)return;apiPost<{players:any[]}>('/api/social/list',{mode:'suggestions'}).then(d=>setSuggestions(d.players||[])).catch(()=>{});},[demo]);
 useEffect(()=>{if(panel==='gifts'&&!demo)apiPost<{gifts:any[]}>('/api/social/action',{type:'inbox'}).then(d=>setGifts(d.gifts||[])).catch(e=>setMessage(e.message));},[panel,demo,setMessage]);
 if(!state)return <main className="center-screen"><Icon name="cup" size={58}/><h1>{error?'Seu café precisa de atenção':'Preparando o CaféVille'}</h1><p>{error||'Acendendo os fogões e abrindo as janelas…'}</p>{error&&<><button className="primary-btn" onClick={()=>location.reload()}>Tentar novamente</button><Link href="/cadastro">Concluir meu perfil</Link><Link href="/login">Voltar ao login</Link></>}</main>;
 const {player:p,cafe:c}=state;
 const liveNow=now+serverOffset.current; // Display only; the server validates every timer.
 const selectedObject=c.layout.find(f=>f.id===selected),inventoryObject=c.inventory.find(f=>f.id===placing),selectedItem=state.items.find(i=>i.id===selectedObject?.itemId),xpGoal=p.level*100;
 const fire=async(a:Action)=>{const ok=await run(a);if(ok&&a.type==='place')setPlacing('');return ok;};
 const enterEdit=async()=>{if(!editing){previousOpen.current=c.open;if(await fire({type:'open',open:false})){setEditing(true);setPanel('inventory');setSelected('');}}else{if(await fire({type:'open',open:previousOpen.current})){setEditing(false);setPlacing('');setSelected('');}}};
 const selectPanel=(key:string)=>{setPanel(key);if(key==='inventory'&&!editing)void enterEdit();if(window.innerWidth<1000&&key!=='inventory')requestAnimationFrame(()=>document.querySelector('.activity-panel')?.scrollIntoView({behavior:'smooth',block:'start'}));};
 const chooseStove=(id:string)=>{const job=c.jobs.find(j=>j.stoveId===id);if(job&&liveNow>=job.spoilsAt)void fire({type:'cleanStove',stoveId:id});else if(job&&liveNow>=job.readyAt)void fire({type:'collect',stoveId:id});else{setStove(id);setPanel('recipes');setMessage(job?'Essa receita ainda está no fogo.':'Escolha uma receita para este fogão.');}};
 const social=async(type:string,targetUid:string)=>{try{await apiPost(type==='follow'?'/api/social/follow':'/api/social/action',type==='follow'?{targetUid,action:'follow'}:{type:'dismiss',targetUid});setSuggestions(v=>v.filter(x=>x.uid!==targetUid));}catch(e){setMessage(e instanceof Error?e.message:'Tente novamente.');}};

 return <div className="game-app">
  <header className="game-header"><Link className="game-brand" href={demo?'/':'/jogo'}><Icon name="chef" size={42}/><span>Café<span>Ville</span></span></Link><nav className="header-links"><Link href={demo?'/demo':'/jogo'} className="active">Meu café</Link><Link href="/comunidade">Vizinhos</Link><Link href="/ranking">Ranking</Link>{p.role==='admin'&&<Link href="/admin">Admin</Link>}</nav><div className="wallet"><span title="Moedas"><Icon name="coin"/>{money(p.coins)}</span><span title="Estrelas especiais: ganhas ao subir de nível"><Icon name="gem"/>{p.gems||0}</span><span title="Popularidade"><Icon name="heart"/>{p.popularity.toFixed(0)}%</span></div><button className="sound-button" aria-label={sound?'Desligar música':'Ligar música'} onClick={()=>{if(sound)audio.current.stop();else audio.current.start();setSound(!sound);}}><Icon name={sound?'volume':'mute'}/></button></header>
  {demo&&<div className="demo-banner">Modo demonstração · O progresso fica neste navegador. <Link href="/cadastro">Criar minha conta</Link></div>}
  <main className="game-layout">
   <aside className="game-rail">{tabs.map(([icon,label,key])=><button key={key} className={panel===key?'active':''} onClick={()=>selectPanel(key)}><Icon name={icon} size={31}/><span>{label}</span></button>)}<div className="rail-spacer"/><button onClick={()=>demo?setMessage('Crie uma conta para convidar seus amigos.'):setInvite(true)}><Icon name="users" size={31}/><span>Convidar</span></button><button onClick={()=>setPanel('expand')}><Icon name="expand" size={31}/><span>Expandir</span></button></aside>
   <section className="cafe-column"><div className="cafe-heading"><div className="chef-profile"><div className="portrait"><GameArt src="/assets/game/characters/chef-0.svg" alt="Seu chef" portrait/></div><div><b>{p.displayName}</b><small>Nível {p.level} · {p.xp}/{xpGoal} XP</small><div className="xp-track"><i style={{width:`${Math.min(100,p.xp/xpGoal*100)}%`}}/></div></div></div><div className="cafe-name"><h1>{c.name}</h1><button onClick={()=>{setNewName(c.name);setRename(true);}} aria-label="Mudar nome do café"><Icon name="edit" size={16}/></button><span>{c.size} × {c.size} · {c.progress.total.served} clientes atendidos</span></div><button disabled={busy||editing} className={`open-sign ${c.open?'':'closed'}`} onClick={()=>fire({type:'open',open:!c.open})}><i/>{c.open?'Aberto':'Fechado'}</button></div>
    <div className={`cafe-frame ${editing?'is-editing':''}`}><CafeGame state={state} editing={editing} selected={selected} placing={inventoryObject?.itemId||''} rotation={rotation} bridge={{select:id=>{setSelected(id);setPlacing('');},move:(id,x,y)=>{void fire({type:'move',id,x,y});},place:(x,y)=>{if(placing)void fire({type:'place',id:placing,x,y,rotation});},stove:chooseStove,notice:setMessage}}/>
     {editing&&<div className="edit-toolbar"><b>{inventoryObject?'Posicionar móvel':selectedItem?.name||'Seu café, do seu jeito'}</b>{selectedObject&&<><button disabled={busy} onClick={()=>fire({type:'rotate',id:selected})}>Girar</button><button disabled={busy} onClick={()=>fire({type:'store',id:selected})}>Guardar</button><button disabled={busy} onClick={()=>fire({type:'sell',id:selected})}>Vender · {money((selectedItem?.price||0)*.4)}</button></>}{inventoryObject&&<button onClick={()=>setRotation(r=>(r+1)%4)}>Girar prévia</button>}<button className="green" disabled={busy} onClick={enterEdit}>Concluir</button></div>}
    </div>
    <div className="game-toast" role="status"><Icon name={online&&!error?'leaf':'clock'} size={20}/><span>{!online?'Sem conexão. Os preparos continuam; reconecte para salvar ações.':error||message}</span>{busy&&<small>Salvando…</small>}</div>
    <section className="kitchen-strip"><div className="strip-title"><Icon name="chef" size={28}/><div><b>Na sua cozinha</b><small>{c.jobs.length} preparando · {Object.values(c.counters).reduce((a,s)=>a+s.portions,0)} porções no balcão</small></div></div><div className="stove-list">{c.layout.filter(f=>state.items.find(i=>i.id===f.itemId)?.kind==='stove').map((f,i)=>{const job=c.jobs.find(j=>j.stoveId===f.id),ready=job&&liveNow>=job.readyAt,spoiled=job&&liveNow>=job.spoilsAt;return <button disabled={busy||editing} className={`stove-card ${spoiled?'spoiled':ready?'ready':''}`} key={f.id} onClick={()=>chooseStove(f.id)}><GameArt src={job?.recipe.art||'/assets/game/appliances/stove.svg'} itemId={job?undefined:f.itemId}/><span><b>{job?.recipe.name||`Fogão ${i+1}`}</b><small>{spoiled?'Estragou · limpar':ready?'Pronto · recolher':job?`${duration(Math.max(0,Math.ceil((job.readyAt-liveNow)/1000)))} restantes`:'Livre · cozinhar'}</small></span>{job&&!ready&&<i style={{width:`${Math.min(100,Math.max(0,(liveNow-job.startedAt)/(job.readyAt-job.startedAt)*100))}%`}}/>}</button>;})}</div></section>
    {suggestions.length>0&&<section className="invite-suggestion"><Icon name="gift" size={34}/><div><b>{suggestions[0].displayName}</b><p>{suggestions[0].reason}</p></div><Link href={`/jogador/${suggestions[0].uid}`}>Visitar</Link><button onClick={()=>social('follow',suggestions[0].uid)}>Seguir</button><button onClick={()=>social('dismiss',suggestions[0].uid)}>Agora não</button></section>}
    <div className="neighborhood"><Icon name="users" size={28}/><div><b>Um bom café é melhor com amigos.</b><span>Visite, presenteie e conheça novos cantinhos.</span></div><Link href="/comunidade">Explorar a vizinhança <span>→</span></Link></div>
   </section>
   <aside className="activity-panel" hidden={panel==='none'}><div className="activity-title"><div><small>FAÇA SEU CAFÉ CRESCER</small><h2>{panel==='recipes'?'Livro de receitas':panel==='shop'?'Loja da vila':panel==='staff'?'Nossa equipe':panel==='inventory'?'Seu inventário':panel==='missions'?'Pequenas conquistas':panel==='expand'?'Um café maior':panel==='more'?'Seu CaféVille':'Caixa de presentes'}</h2></div><Icon name={panel==='recipes'?'book':panel==='shop'?'shop':panel==='missions'?'flag':'gift'} size={36}/></div>
   {panel==='more'&&<div className="more-menu">{tabs.map(([icon,label,key])=><button key={key} onClick={()=>selectPanel(key)}><Icon name={icon}/>{label}</button>)}<button onClick={()=>setPanel('expand')}><Icon name="expand"/>Expandir</button><button onClick={()=>demo?setMessage('Crie uma conta para convidar amigos.'):setInvite(true)}><Icon name="users"/>Convidar amigos</button><Link href="/ranking"><Icon name="star"/>Ranking</Link></div>}
   {panel==='recipes'&&<><p className="panel-intro">{stove?'Receitas para o fogão selecionado.':'Escolha um prato. O chef cuida do preparo.'}</p><div className="pills">{['Todas','Bebidas','Salgados','Doces','Pratos'].map(v=><button className={filter===v?'active':''} key={v} onClick={()=>setFilter(v)}>{v}</button>)}</div><div className="recipe-cards">{state.recipes.filter(r=>r.active!==false&&(filter==='Todas'||r.category===filter)).map(r=><article className={`new-recipe ${p.level<r.level?'locked':''}`} key={r.id}><div className="food-picture"><img src={r.art} alt={r.name}/><span><Icon name="clock" size={14}/>{duration(r.seconds)}</span></div><h3>{r.name}</h3><div className="recipe-reward"><span><Icon name="coin" size={15}/>{r.cost}</span><span><Icon name="star" size={15}/>+{r.xp} XP</span></div><p>{r.portions} porções · {r.price} moedas cada</p><small>Recolha em até {duration(r.shelfSeconds)}</small><button disabled={busy||!online||editing||p.level<r.level||p.coins<r.cost} onClick={async()=>{const chosen=c.jobs.some(j=>j.stoveId===stove)?'':stove;await fire({type:'cook',recipeId:r.id,...(chosen?{stoveId:chosen}:{})});setStove('');}}>{p.level<r.level?`Nível ${r.level}`:p.coins<r.cost?'Faltam moedas':'Cozinhar'}</button></article>)}</div>{(state.legacyJobs?.length||0)>0&&<div className="legacy-jobs"><h3>Preparos da versão anterior</h3>{state.legacyJobs!.map(j=><button disabled={busy||now<j.readyAt} key={j.id} onClick={async()=>{try{await apiPost('/api/recipes/collect',{jobId:j.id});await refresh();setMessage('Preparo anterior resgatado.');}catch(e){setMessage(e instanceof Error?e.message:'Tente novamente.');}}}>{j.recipeName} · {now<j.readyAt?duration(Math.ceil((j.readyAt-now)/1000)):'Resgatar'}</button>)}</div>}</>}
   {panel==='shop'&&<><p className="panel-intro">Encontre algo que tenha a sua cara.</p><div className="pills">{Object.keys(categories).map(v=><button key={v} className={shopFilter===v?'active':''} onClick={()=>setShopFilter(v)}>{v}</button>)}</div><div className="shop-cards">{state.items.filter(i=>i.active!==false&&(!categories[shopFilter]||i.kind===categories[shopFilter])).map(i=><article className="shop-card" key={i.id}><GameArt src={i.art} itemId={i.id} alt={i.name}/><b>{i.name}</b><small>{i.width} × {i.height} · Nível {i.level}</small><strong><Icon name="coin" size={17}/>{money(i.price)}</strong><button disabled={busy||p.level<i.level||p.coins<i.price||c.ownedStyles.includes(i.id)} onClick={()=>fire({type:'buy',itemId:i.id})}>{c.ownedStyles.includes(i.id)?'Você já tem':p.level<i.level?`Nível ${i.level}`:'Comprar'}</button></article>)}</div></>}
   {panel==='inventory'&&<><p className="panel-intro">Escolha um item guardado e toque na grade. Toque nos móveis do café para editar.</p><div className="shop-cards">{c.inventory.map(f=>{const item=state.items.find(i=>i.id===f.itemId);return <article key={f.id} className={`shop-card ${placing===f.id?'chosen':''}`}><GameArt src={item?.art} itemId={f.itemId} alt={item?.name||f.itemId}/><b>{item?.name||f.itemId}</b><button disabled={busy} onClick={()=>{setSelected('');setPlacing(f.id);setRotation(0);}}>Posicionar</button><button className="quiet" disabled={busy} onClick={()=>fire({type:'sell',id:f.id})}>Vender · {money((item?.price||0)*.4)}</button></article>;})}</div>{!c.inventory.length&&<div className="empty-state"><Icon name="box" size={54}/><b>Tudo está no seu café</b><p>Guarde um móvel ou encontre algo novo na loja.</p><button onClick={()=>setPanel('shop')}>Visitar a loja</button></div>}<h3 className="sub-title">Acabamentos que você tem</h3><div className="styles-list">{state.items.filter(i=>isStyle(i.kind)&&c.ownedStyles.includes(i.id)).map(i=><button key={i.id} disabled={busy} onClick={()=>fire({type:'style',itemId:i.id})}><GameArt src={i.art} itemId={i.id}/>{i.name}</button>)}</div></>}
   {panel==='staff'&&<><p className="panel-intro">Seu trio já está contratado. Cuide de quem cuida do café.</p>{(['chef','waiter','cleaner'] as const).map((role,i)=><article className="worker-card" key={role}><GameArt src={`/assets/game/characters/${role}-0.svg`}/><div><h3>{['Chef','Garçom','Faxineira'][i]}</h3><b>Nível {c.staff[role]} de 5</b><p>{['Preparo até 20% mais rápido.','Caminha, busca e serve os pedidos.','Limpa mesas para os próximos clientes.'][i]}</p><button disabled={busy||c.staff[role]>=5||p.coins<c.staff[role]*400} onClick={()=>fire({type:'upgrade',role})}>{c.staff[role]>=5?'Nível máximo':`Melhorar · ${money(c.staff[role]*400)}`}</button></div></article>)}</>}
   {panel==='missions'&&<><div className="pills">{(['daily','weekly','total'] as const).map((v,i)=><button className={period===v?'active':''} key={v} onClick={()=>setPeriod(v)}>{['Diárias','Semanais','Conquistas'][i]}</button>)}</div>{MISSIONS.filter(m=>m.period===period).map(m=>{const value=c.progress[m.period][m.stat],claimed=c.progress.claimed.includes(missionKey(c.progress,m.period,m.id));return <article className="quest-card" key={m.id}><div><h3>{m.name}</h3><span>{Math.min(value,m.target)} / {m.target} · {({served:'clientes atendidos',cooked:'receitas recolhidas',visits:'cafés visitados',bought:'compras',earned:'moedas em vendas',helped:'ajudas'})[m.stat]}</span></div><div className="quest-track"><i style={{width:`${Math.min(100,value/m.target*100)}%`}}/></div><footer><span><Icon name="coin" size={17}/>{m.coins} <Icon name="star" size={17}/>{m.xp}</span><button disabled={busy||claimed||value<m.target} onClick={()=>fire({type:'mission',missionId:m.id})}>{claimed?'Recebido':value>=m.target?'Receber':'Em andamento'}</button></footer></article>;})}{state.events.filter(e=>e.active&&e.startAt<now&&e.endAt>now).map(e=><article className="quest-card event-card" key={e.id}><small>EVENTO DA VILA</small><h3>{e.name}</h3><p>{e.description}</p><p>{c.progress.weekly.served}/{e.target} clientes nesta semana</p><button disabled={busy||c.progress.weekly.served<e.target||c.appliedCampaigns.includes(`event-${e.id}`)} onClick={()=>fire({type:'event',eventId:e.id})}>Receber {e.coins} moedas</button></article>)}</>}
   {panel==='expand'&&<><p className="panel-intro">Mais espaço para receber, decorar e criar.</p>{EXPANSIONS.map(e=><article className="expansion-card" key={e.size}><Icon name="expand" size={46}/><h3>{e.size} × {e.size}</h3><p>Nível {e.level} · {money(e.cost)} moedas</p><button disabled={busy||e.size<=c.size||EXPANSIONS.find(x=>x.size>c.size)?.size!==e.size||p.level<e.level||p.coins<e.cost} onClick={()=>fire({type:'expand'})}>{e.size<=c.size?'Conquistado':'Expandir café'}</button></article>)}<p className="panel-intro">A estrutura para futuras filiais está preparada. A abertura do Café da Praia será lançada em uma próxima versão.</p></>}
   {panel==='gifts'&&<>{demo?<div className="empty-state"><Icon name="gift" size={60}/><h3>Um carinho da vizinhança</h3><p>Crie sua conta para trocar presentes.</p><Link className="green" href="/cadastro">Criar minha conta</Link></div>:gifts.length?gifts.map(g=><article className="quest-card" key={g.id}><h3>{g.title}</h3><p>De {g.fromName||'Equipe CaféVille'}</p><button onClick={async()=>{try{await apiPost('/api/social/action',{type:'accept',giftId:g.id,requestId:crypto.randomUUID()});setGifts(v=>v.filter(x=>x.id!==g.id));await refresh();setMessage('Presente recebido!');}catch(e){setMessage(e instanceof Error?e.message:'Tente novamente.');}}}>Aceitar presente</button></article>):<div className="empty-state"><Icon name="gift" size={58}/><h3>Caixa de presentes vazia</h3><p>Visite seus vizinhos e envie o primeiro carinho.</p><Link href="/comunidade">Encontrar vizinhos →</Link></div>}</>}
   </aside>
  </main><nav className="game-mobile-nav"><button onClick={()=>setPanel('none')}><Icon name="home"/><span>Início</span></button><button onClick={()=>selectPanel('recipes')}><Icon name="book"/><span>Receitas</span></button><button onClick={()=>selectPanel('shop')}><Icon name="shop"/><span>Loja</span></button><Link href="/comunidade"><Icon name="users"/><span>Amigos</span></Link><button onClick={()=>selectPanel('more')}><Icon name="more"/><span>Mais</span></button></nav>
  <footer className="game-footer"><span>CaféVille · Feito para bons encontros</span>{demo?<Link href="/login">Entrar na minha conta</Link>:<button onClick={()=>signOut(auth)}>Sair da conta</button>}</footer>
  <InviteModal open={invite} onClose={()=>setInvite(false)}/>
  {levelUp>0&&<div className="cv-modal-backdrop"><section className="level-celebration"><Icon name="star" size={90}/><small>SEU CAFÉ ESTÁ CRESCENDO</small><h2>Novo nível!</h2><strong>{levelUp}</strong><p>Moedas bônus e 1 estrela especial por nível.<br/>Veja as novidades no livro e na loja!</p><button onClick={()=>setLevelUp(0)}>Vamos comemorar</button></section></div>}
  {rename&&<div className="cv-modal-backdrop"><form className="cv-modal" onSubmit={async e=>{e.preventDefault();if(await fire({type:'rename',name:newName}))setRename(false);}}><h2>Como se chama seu café?</h2><input className="name-input" value={newName} onChange={e=>setNewName(e.target.value)} minLength={3} maxLength={32} required autoFocus/><button disabled={busy} className="primary-btn">Salvar nome</button><button className="quiet" type="button" onClick={()=>setRename(false)}>Cancelar</button></form></div>}
 </div>;
}
