"""Bundle the original game art into next.config.ts for reliable web uploads.

This packages existing image bytes; it never modifies or regenerates PNG art.
Run with Python 3 after intentionally updating the checked-in asset files.
"""
from pathlib import Path
import base64
import gzip
import hashlib
import json
import textwrap

root = Path(__file__).resolve().parents[1]
assets_root = root / 'public/assets/game'
assets = []
for source in sorted(assets_root.rglob('*')):
    if source.suffix not in {'.svg', '.png'}:
        continue
    raw = source.read_bytes()
    assets.append({
        'path': source.relative_to(assets_root).as_posix(),
        'encoding': 'base64' if source.suffix == '.png' else 'utf8',
        'data': base64.b64encode(raw).decode('ascii') if source.suffix == '.png' else raw.decode('utf8'),
        'sha256': hashlib.sha256(raw).hexdigest(),
    })

encoded = base64.b64encode(gzip.compress(
    json.dumps(assets, ensure_ascii=False, separators=(',', ':')).encode('utf8'),
    compresslevel=9, mtime=0,
)).decode('ascii')

header = '''import type { NextConfig } from "next";
import { PHASE_DEVELOPMENT_SERVER, PHASE_PRODUCTION_BUILD } from "next/constants";
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { gunzipSync } from "node:zlib";
import { createHash } from "node:crypto";

/** CafeVille 0.5: original SVGs and illustrated PNG atlases.
 * Generated by scripts/build-art-pack.py. This bundle contains only game art.
 * Images are restored before build/dev, so uploading the code update is enough.
 * No file is created during the production server phase.
 */
const GAME_ART_PACK = `
'''
footer = '''
`;

type PackedAsset = {path:string;encoding:"utf8"|"base64";data:string;sha256:string};

function ensureGameArt(): void {
  const assets = JSON.parse(gunzipSync(Buffer.from(GAME_ART_PACK, "base64")).toString("utf8")) as PackedAsset[];
  const base = join(process.cwd(), "public", "assets", "game");
  const allowed = /^(appliances|characters|decor|effects|floors|food|furniture|ui|walls|nostalgia-v5)\\/[a-z0-9_-]+\\.(svg|png)$/;
  let restored = 0;
  for (const asset of assets) {
    if (!allowed.test(asset.path) || typeof asset.data !== "string" || !/^[a-f0-9]{64}$/.test(asset.sha256) || !["utf8", "base64"].includes(asset.encoding)) {
      throw new Error("CafeVille: pacote de imagens invalido.");
    }
    const destination = join(base, asset.path);
    if (existsSync(destination) && statSync(destination).size > 0) {
      // Preserve existing editable SVG artwork; the versioned PNG atlas must match its frame map.
      if (asset.encoding === "utf8" || createHash("sha256").update(readFileSync(destination)).digest("hex") === asset.sha256) continue;
    }
    const bytes = Buffer.from(asset.data, asset.encoding);
    if (createHash("sha256").update(bytes).digest("hex") !== asset.sha256) throw new Error("CafeVille: imagem incompleta no pacote.");
    mkdirSync(dirname(destination), {recursive:true});
    writeFileSync(destination, bytes);
    restored++;
  }
  if (restored) console.info(`[CafeVille] ${restored} imagens preparadas para o jogo.`);
}

export default function nextConfig(phase:string): NextConfig {
  if (phase === PHASE_PRODUCTION_BUILD || phase === PHASE_DEVELOPMENT_SERVER) ensureGameArt();
  return {reactStrictMode:true};
}
'''
(root / 'next.config.ts').write_text(header + '\n'.join(textwrap.wrap(encoded, 120)) + footer)
print(f'Packed {len(assets)} assets into next.config.ts ({len(encoded):,} base64 characters).')
