"use client";
import AuthGuard from '@/components/AuthGuard';
import TopBar from '@/components/TopBar';
import Icon from '@/components/Icon';
import { apiPost } from '@/lib/api';
import Link from 'next/link';
import { useEffect,useState } from 'react';
function Ranking(){const [mode,setMode]=useState('global'),[players,setPlayers]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);useEffect(()=>{let active=true;setLoading(true);setError('');apiPost('/api/ranking',{mode}).then(d=>{if(active)setPlayers(d.players||[]);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[mode]);return <div className="game-app"><TopBar/><main className="social-page"><div className="social-title"><div><small>OS QUERIDINHOS DA VILA</small><h1>Um lugar entre os melhores</h1><p>Cada prato e cada bom atendimento contam.</p></div><Icon name="star" size={70}/></div><div className="pills ranking-pills">{[['global','Global'],['friends','Amigos'],['week','Semana'],['popularity','Popularidade'],['level','Nível']].map(([k,v])=><button className={mode===k?'active':''} key={k} onClick={()=>setMode(k)}>{v}</button>)}</div>{error&&<p className="error-box">{error}</p>}{loading?<p>Buscando os cafés…</p>:<><div className="rank-podium">{players.slice(0,3).map((p,i)=><Link href={`/jogador/${p.uid}`} key={p.uid}><Icon name="star" size={44}/><span>#{i+1}</span><img src={`/assets/game/characters/guest${i}-0.svg`} alt=""/><h2>{p.displayName}</h2><small>@{p.username}</small><b>{mode==='week'?`${p.weekScore||0} XP na semana`:`Nível ${p.level}`}</b></Link>)}</div><div className="rank-list">{players.map((p,i)=><Link href={`/jogador/${p.uid}`} key={p.uid}><b>#{i+1}</b><div><strong>{p.displayName}</strong><small>{p.cafeName}</small></div><span>Nv. {p.level}</span><span>{p.popularity.toFixed(0)}%</span><span>{p.followersCount||0} seguidores</span><span>{mode==='week'?p.weekScore||0:(p.level-1)*p.level*50+p.xp} XP</span></Link>)}</div>{!players.length&&<p>Nenhum café neste ranking ainda. Abra o seu e comece a jogar!</p>}<p className="rank-note">Semana: segunda a domingo, horário de Brasília. Ranking de amigos considera até 200 cafés seguidos; os demais mostram os 50 primeiros.</p></>}</main></div>;}
export default function RankingPage(){return <AuthGuard><Ranking/></AuthGuard>;}
